apiVersion: v1
kind: Namespace
metadata:
  name: console-node-healthcheck-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-node-healthcheck-plugin
  namespace: console-node-healthcheck-plugin
  labels:
    app: console-node-healthcheck-plugin
    app.kubernetes.io/component: console-node-healthcheck-plugin
    app.kubernetes.io/instance: console-node-healthcheck-plugin
    app.kubernetes.io/part-of: console-node-healthcheck-plugin
    app.openshift.io/runtime-namespace: console-node-healthcheck-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-node-healthcheck-plugin
  template:
    metadata:
      labels:
        app: console-node-healthcheck-plugin
    spec:
      containers:
        - name: console-node-healthcheck-plugin
          image: quay.io/jcaianirh/console-node-healthcheck-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: console-node-healthcheck-plugin
  namespace: console-node-healthcheck-plugin
  labels:
    app: console-node-healthcheck-plugin
    app.kubernetes.io/component: console-node-healthcheck-plugin
    app.kubernetes.io/instance: console-node-healthcheck-plugin
    app.kubernetes.io/part-of: console-node-healthcheck-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: console-node-healthcheck-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: console-node-healthcheck-plugin
spec:
  displayName: 'OpenShift Console node-healthcheck Plugin'
  service:
    name: console-node-healthcheck-plugin
    namespace: console-node-healthcheck-plugin
    port: 9001
    basePath: '/'
  proxy:
    - type: Service
      alias: thanos-querier
      authorize: true
      service:
        name: thanos-querier
        namespace: openshift-monitoring
        port: 9091
